apiVersion: apps/v1
kind: Deployment
metadata:
    name: jenkins-deployment
    namespace: jenkins-dev
spec:
    replicas: 1
    selector:
        matchLabels:
            app: jenkins
    template:
        metadata:
            labels:
                app: jenkins
                role: controller
        spec:
            containers:
                -   name: jenkins
                    image: setmyinfo/setmy-info-rocky-java-jenkins:latest
                    env:
                        -   name: SMI_JENKINS_ROLE
                            value: "controller"
                        -   name: SMI_JENKINS_PORT
                            value: "7070"
                        -   name: SMI_JENKINS_HOST
                            value: "0.0.0.0"
                        -   name: SMI_JENKINS_HOME
                            value: "/var/lib/jenkins"
                        -   name: JENKINS_URL
                            valueFrom:
                                configMapKeyRef:
                                    name: jenkins-config-map
                                    key: jenkins-url
                                    optional: false
                        -   name: GITHUB_TOKEN
                            valueFrom:
                                secretKeyRef:
                                    name: jenkins-secrets-map
                                    key: github-token
                                    optional: false
                        -   name: GITHUB_USERNAME
                            valueFrom:
                                secretKeyRef:
                                    name: jenkins-secrets-map
                                    key: github-username
                                    optional: false
                    ports:
                        -   name: http
                            containerPort: 7070
                    readinessProbe:
                        httpGet:
                            path: /login
                            port: http
                        initialDelaySeconds: 30
                        periodSeconds: 10
                    livenessProbe:
                        httpGet:
                            path: /login
                            port: http
                        initialDelaySeconds: 120
                        periodSeconds: 30
#                    volumeMounts:
#                        -   name: gintra
#                            mountPath: /mnt/gintra
#            volumes:
#                -   name: gintra
#                    persistentVolumeClaim:
#                        claimName: jenkins-nfs-persistent-volume-claim
