#!/bin/sh

echo "Should be root: $(whoami)"

SMI_JENKINS_ROLE=$(do-role)

processInstallation() {
    #mkdir -p /mnt/gintra/ee/has/development/software/packages
    mkdir -p ~/.setmy.info/packages

    #echo "Files in /mnt/gintra/ee/has/development/software/packages"
    #ls -la /mnt/gintra/ee/has/development/software/packages

    #echo "Files in ~/.setmy.info/packages"
    #ls -la ~/.setmy.info/packages

    #smi-sync /mnt/gintra/ee/has/development/software/packages/ ~/.setmy.info/packages/

    #echo "After sync files in ~/.setmy.info/packages"
    #ls -la ~/.setmy.info/packages

    smi-download-package ${SMI_PACKAGES}
    #smi-sync ~/.setmy.info/packages/ /mnt/gintra/ee/has/development/software/packages/
    smi-install-package ${SMI_PACKAGES}
}

if [ "${SMI_JENKINS_ROLE}" = "node" ]; then
    processInstallation
else
    echo "Role ${SMI_JENKINS_ROLE}: the build tools belong to the nodes, none are installed"
fi

exit 0

